if then else
  boolbool byte if then else loop input lalalooplala output return


  asdasdas%%##asdasd

  ; , :
  [  (   ) ]
  {  +=- }
  */<>=!&$

<= >= == != && ||

asd
asd8asd
asd_asd
8asd
8_
100

/*
COMENTARIO
*/
asdasd/*asd
outro comentário
asd*/asd
if asd//asdasd
if // eu sou um comentário 
"LALALALA LALA    LALALALA" 'a'
100 100 100 100
if else then bool loop 
lala 10asd 10as1203d a5
"lala"

